### ISSUE TITLE
Port to 1.12.2?

### ISSUE THREAD

**Issue by fuzzyray** [Turkey2349/TurkeyUtil#1]
This is just a request, but how much bribery would I need to get this ported to 1.12.2 for Vanilla Twist? 
Failing that would it be possible to just get a small mod with the rock soup and Kiraeyl's Turkey feather for 1.12.2?

Because if you don't do it, I will have to learn how to mod :P

**Comment by Funwayguy** [comment]
_sends over programming tutorials_

We can always use more ~~slaves~~ developers

EDIT: [Related note from Turkey last year](https://blog.theprogrammingturkey.com/2017/08/10/the-post-i-never-wanted-to-make/)

**Comment by TheTurkeyDev** [comment]
Sadly yes, I just don't have the time to port this mod as it is just too large. I did have someone say they were interested in taking it over and porting and working on it them selves, but I have not heard anything from them recently.

**Comment by fuzzyray** [comment]
Funwayguy, if you actually have decent modding tutorials, go ahead and send them. I do know how to program, I just hate doing it in Java. But I could start small and port the soup and feather initially.

**Comment by fuzzyray** [comment]
Still wouldn't mind anything either one of you could throw my way for modding documentation. Been finding a ton of garbage out there. But managed to piece together enough to make the kirafeather mod. As I learn more about the specifics of modding, I'll look at what it takes to port this forward.

**Comment by TheTurkeyDev** [comment]
Feel free to look at my projects and the 1.12 branches of them. I can try to answer questions if you have them, just pm me.

**Comment by Funwayguy** [comment]
Same here with questions. I'm almost always available on Discord if you need to ask anything. As for tutorials [McJty usually has some pretty good overviews](https://wiki.mcjty.eu/modding/index.php?title=Main_Page) on how to do the basics for 1.12 with source code.
